# -*- coding: utf-8 -*-
"""module4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MziIgys46NUsotdJ5PmoJVANVRWO7dpM
"""

try:
    n = int(input("Enter the number of elements (N): "))
except ValueError:
    print("Invalid input. Please enter an integer.")
    exit()

numbers = []
print(f"Please provide {n} numbers:")
for i in range(n):
    try:
        num = int(input(f"Enter number {i + 1}: "))
        numbers.append(num)
    except ValueError:
        print("Invalid input. Please enter an integer.")
        numbers.append(0)

try:
    x = int(input("Enter the number to search for (X): "))
except ValueError:
    print("Invalid input. Please enter an integer.")
    exit()

try:
    zero_based_index = numbers.index(x)
    print(zero_based_index + 1)
except ValueError:
    print("-1")