# -*- coding: utf-8 -*-
"""module6_knn-regr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RZ4BvldZ4kNHIfcn1-bitdJR9IFIM9v
"""

import numpy as np

def knn_regression(N, k, points, X_new):
    if k > N:
        return f"Error: The number of neighbors (k={k}) must be less than or equal to the number of data points (N={N})."

    X_train = points[:, 0]
    Y_train = points[:, 1]

    distances = np.abs(X_train - X_new)

    k_nearest_indices = np.argsort(distances)[:k]

    k_nearest_Y = Y_train[k_nearest_indices]

    Y_pred = np.mean(k_nearest_Y)

    return Y_pred

while True:
    try:
        N = int(input("Enter the total number of data points (N, positive integer): "))
        if N <= 0:
            raise ValueError
        break
    except ValueError:
        print("Invalid input. Please enter a positive integer for N.")

while True:
    try:
        k = int(input("Enter the number of neighbors (k, positive integer): "))
        if k <= 0:
            raise ValueError
        break
    except ValueError:
        print("Invalid input. Please enter a positive integer for k.")

print(f"\nPlease provide {N} (x, y) points:")
data_points = np.empty((N, 2), dtype=float)

for i in range(N):
    while True:
        try:
            x = float(input(f"  Point {i+1}/{N}: Enter x value (real number): "))
            y = float(input(f"  Point {i+1}/{N}: Enter y value (real number): "))
            data_points[i, 0] = x
            data_points[i, 1] = y
            break
        except ValueError:
            print("Invalid input. Please enter a real number for both x and y.")

while True:
    try:
        X_target = float(input("\nSuccessfully read all points. Enter the target X value for prediction: "))
        break
    except ValueError:
        print("Invalid input. Please enter a real number for the target X.")

result = knn_regression(N, k, data_points, X_target)

if isinstance(result, str) and result.startswith("Error"):
    print(f"\n{result}")
else:
    print(f"\nk-NN Regression Result (Predicted Y for X={X_target}): {result:.4f}")