# -*- coding: utf-8 -*-
"""module5_oop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oxEYiuO_Pd4Vjg1uPLqmkDrNCkxR-Dh6
"""

class NumberStore:

    def __init__(self):
        self.numbers = []

    def add_number(self, number):
        self.numbers.append(number)

    def find_index(self, x):
        try:
            zero_based_index = self.numbers.index(x)

            return zero_based_index + 1

        except ValueError:
            return -1

def main():
    store = NumberStore()

    try:
        n = int(input("Enter the total number of elements (N): "))
        if n <= 0:
            print("N must be a positive number.")
            return
    except ValueError:
        print("Invalid input. Please enter an integer.")
        return
    print(f"\nPlease enter {n} numbers, one by one:")
    for i in range(n):
        try:
            num = int(input(f"Enter number {i + 1}: "))

            store.add_number(num)
        except ValueError:
            print("Invalid input. Please enter an integer.")
            print("Restart the program and enter valid numbers.")
            return

    print("\n--- Search Phase ---")
    try:
        x = int(input("Enter the number to search for (X): "))

        result = store.find_index(x)

        print(f"\nOutput: {result}")

    except ValueError:
        print("Invalid input. Please enter an integer.")

if __name__ == "__main__":
    main()