# -*- coding: utf-8 -*-
"""module5_mod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dzuQubWqmsWH5_9BfVherx5SpsUwumuY
"""

class NumberStore:

    def __init__(self):
        self.numbers = []

    def add_number(self, number):
        self.numbers.append(number)

    def find_index(self, x):
        try:
            zero_based_index = self.numbers.index(x)

            return zero_based_index + 1

        except ValueError:
            return -1