# -*- coding: utf-8 -*-
"""module5_call.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YEk-dOVM0waJsu3aLLsr-TGykWntuSH
"""

from module5_mod import NumberStore

def main():
    store = NumberStore()

    try:
        n = int(input("Enter the total number of elements (N): "))
        if n <= 0:
            print("N must be a positive number.")
            return
    except ValueError:
        print("Invalid input. Please enter an integer.")
        return

    print(f"\nPlease enter {n} numbers, one by one:")
    for i in range(n):
        try:
            num = int(input(f"Enter number {i + 1}: "))
            store.add_number(num)
        except ValueError:
            print("Invalid input. Please enter an integer.")
            print("Restart the program and enter valid numbers.")
            return

    print("\n--- Search Phase ---")
    try:
        x = int(input("Enter the number to search for (X): "))
        result = store.find_index(x)

        print(f"\nOutput: {result}")

    except ValueError:
        print("Invalid input. Please enter an integer.")
if __name__ == "__main__":
    main()